### ISSUE TITLE
Проработка главного экрана

### ISSUE THREAD

**Issue by Shiplayer** [codex-team/hawk.android#35]
Необходимо разбить на подзадачи главный экран

дизайн [figma](https://www.figma.com/file/0ah2Q1TCRGsXYmrpHExprj/Hawk-Android?node-id=1%3A69)

**Comment by Shiplayer** [comment]
- [x] поисследовать, как мы можем обрезать вьюшки по методу squircle без использования сторонних библиотек #37 
- [x] Сделать кастомную вьюшку для поиска #38
- [x] Сделать кастомную вьюшку для бейджей #39 
- [x] Сделать кастомную вьюшку для отображения картинок #37
- [x] Сделать реализацию апи для получения информации по воркспейсам и проектам #40 #41 
- [x] Добавить RecyclerView для отображения проектов #42
